#
# Copyright(C) 2018, Juniper Networks, Inc.
# All rights reserved
#
# This SOFTWARE is licensed under the license provided in the LICENSE.txt
# file.  By downloading, installing, copying, or otherwise using the
# SOFTWARE, you agree to be bound by the terms of that license.  This
# SOFTWARE is not an official Juniper product.
#
# Third-Party Code: This SOFTWARE may depend on other components under
# separate copyright notice and license terms.  Your use of the source
# code for those components is subject to the term and conditions of
# the respective license as noted in the Third-Party source code.
#

ROOT_PATTERN		= /sqlite/
DEPOT_ROOT			= $(word 1,$(subst $(ROOT_PATTERN), ,$(CURDIR)))
ROOT_PATH			= $(DEPOT_ROOT)$(ROOT_PATTERN)

include $(ROOT_PATH)/Makefile.globals

#
# 3/19/06: GNU Compatible "make" file
# - VPATH specifies dependent location, not target location
#

VPATH				=	$(CURDIR):$(LIB_SOURCE_DIR):$(BUILD_BIN_DIR):$(OBJECT_DIR)

SOURCES				=	sqlite3.c

OBJECT_DIR			=	$(VENDOR_OBJ_DIR)$(PROJECT_DIR)
EXECUTABLE			=	$(VENDOR_LIB_DIR)/libsqlite3.dll
EXTRA_LD_FLAGS			+= 	-dll -def:sqlite3.def
CL_FLAGS			+=	-D_WIN32 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_RTREE

default		: setup $(EXECUTABLE) $(TARGET_PROGRAMS)

include $(ROOT_PATH)/Makefile.build
